# Generated by Django 5.2 on 2025-10-22 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_helpseekertype_donation_latitude_donation_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('donor', 'Donor Verification'), ('help_seeker', 'Help Seeker Verification')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs More Information')], default='pending', max_length=20)),
                ('document', models.FileField(upload_to='verification_docs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes or reason for rejection')),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='donationcategory',
            options={'ordering': ['name'], 'verbose_name': 'Donation Category', 'verbose_name_plural': 'Donation Categories'},
        ),
        migrations.AlterModelOptions(
            name='donationmatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation Match', 'verbose_name_plural': 'Donation Matches'},
        ),
        migrations.AlterModelOptions(
            name='donationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation Request', 'verbose_name_plural': 'Donation Requests'},
        ),
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'verbose_name': 'Donor Profile', 'verbose_name_plural': 'Donor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='helprequest',
            options={'ordering': ['-urgency', '-created_at'], 'verbose_name': 'Help Request', 'verbose_name_plural': 'Help Requests'},
        ),
        migrations.AlterModelOptions(
            name='helpseeker',
            options={'ordering': ['-created_at'], 'verbose_name': 'Help Seeker', 'verbose_name_plural': 'Help Seekers'},
        ),
        migrations.AlterModelOptions(
            name='helpseekertype',
            options={'ordering': ['name'], 'verbose_name': 'Help Seeker Type', 'verbose_name_plural': 'Help Seeker Types'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='donationcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpseeker',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpseeker',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_seekers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpseekertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donorprofile'),
        ),
        migrations.AlterField(
            model_name='donationcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donations.donation'),
        ),
        migrations.AlterField(
            model_name='donationmatch',
            name='help_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donations.helpseeker'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.donation'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='donations.donation'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='help_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='donations.helpseeker'),
        ),
        migrations.AlterField(
            model_name='helpseekertype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='donations.donorprofile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='help_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='donations.helpseeker'),
        ),
        migrations.AlterUniqueTogether(
            name='donationrequest',
            unique_together={('donation', 'requester')},
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'donation')},
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'pickup_deadline'], name='donations_d_status_77b79b_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['category', 'status'], name='donations_d_categor_feb72e_idx'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
